image: Visual Studio 2017
configuration: Release
branches:
  only:
  - master
  - dev
  - /hotfix\/.*/

environment:
  SignClientSecret:
    secure: S26+NphAhj/vo5ZdHd/N/4toty3ztdNGmuNdvAB57W1oIVQEHVKqAVuhTD8B9ATy

init:
  - git config --global core.autocrlf input

install:
  - cmd: appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/v4.1.0/NuGet.exe
  - cmd: nuget install SignClient -Version 0.7.0 -SolutionDir %APPVEYOR_BUILD_FOLDER% -Verbosity quiet -ExcludeVersion
     
before_build:
  - cmd: msbuild /t:restore src\Humanizer.sln
  
build:
  verbosity: normal
  parallel: true
  project: src\Humanizer.sln
  
after_build:
  - ps: |
      $vers = & $env:UserProfile\.nuget\packages\nerdbank.gitversioning\2.0.4-beta\tools\Get-Version.ps1
      $nugetVer = $vers.NuGetPackageVersion
      ls .\NuSpecs\*.nuspec | %{ nuget pack $_.FullName -version "$nugetVer" -BasePath "src" -NoPackageAnalysis }
  - ps: '.\scripts\Sign-Package.ps1'        
  - ps: 'ls *.nupkg | %{ appveyor PushArtifact $_.Name}'
  
test:
  assemblies:
    - '**\*.Tests.dll'
  
deploy:
- provider: NuGet
  server: https://www.myget.org/F/humanizer/api/v2/package
  on:
    branch: master
  api_key:
    secure: bmqlJK8a5HYiUXOT99HXT1j7JiM5+fpR4kHhxIC30oaaEXbv94f0fKdiKlU1QC/l
  artifact: /.*\.nupkg/
  
- provider: NuGet
  server: https://www.myget.org/F/humanizer/api/v2/package
  on:
    branch: dev
  api_key:
    secure: bmqlJK8a5HYiUXOT99HXT1j7JiM5+fpR4kHhxIC30oaaEXbv94f0fKdiKlU1QC/l
  artifact: /.*\.nupkg/  